DROP TABLE IF EXISTS `user_auth`;
CREATE TABLE `user_auth` (
	`no`			BIGINT				NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`			VARCHAR(255)		NOT NULL	COMMENT 'UK',
	`username`		VARCHAR(100)		NOT NULL	COMMENT '아이디',
	`auth`			VARCHAR(100)		NOT NULL	COMMENT '회원권한(ROLE_USER, ROLE_ADMIN)',
	`created_at`	TIMESTAMP			NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP			NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);